version: "3"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: 'rabbitmq:3.8.9-management-alpine'
    hostname: rabbitmq
    ports:
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    env_file:
      - .env.rabbitmq
  redis:
    container_name: "redis"
    image: "redis:6.0.9-alpine"
    ports:
      - "6379:6379"
  redis-commander:
    container_name: "redis-commander"
    image: rediscommander/redis-commander:latest
    restart: always
    env_file:
      - .env.redis
    ports:
      - "8081:8081"
  postgres: 
    container_name: "postgres"
    image: "postgres:9.6.21-alpine"
    restart: "always"
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres
  pgadmin:
    container_name: "pgadmin"
    image: "dpage/pgadmin4:4.30"
    restart: "always"
    ports: 
      - "5050:5050"
    env_file:
      - .env.postgres
      - .env.pgadmin
